# Generated by Django 4.0.3 on 2022-03-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
    ]
