# Generated by Django 4.0.3 on 2022-03-22 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_alter_student_surname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Works',
            new_name='Work',
        ),
    ]
