# Generated by Django 4.0.3 on 2022-03-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_alter_progress_options_work_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='comment',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
