# Generated by Django 4.0.3 on 2022-03-23 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_alter_group_options_alter_work_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['work'], 'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['date'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.work', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата задания'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Задача'),
        ),
    ]
